name: deploy k8s
on:
  workflow_dispatch:

jobs:
  build:
    name: Build da aplicação
    runs-on: arc-runner-set
    # runs-on: arc-runner-set
    steps:
      - uses: actions/checkout@v4 # Action para ter acesso ao repositorio
      - name: Ver conexto
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      # - name: Configuração contexto kuberntes
      #   uses: azure/k8s-set-context@v5 # https://github.com/marketplace/actions/kubernetes-set-context
      #   with:
      #     method: kubeconfig
      #     kubeconfig: ${{ secrets.KUBE_CONFIG }}
      - name: "instalando kubectl"
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - name: "Executando"
        run: kubectl get nodes
