name: deploy k8s
on:
  workflow_dispatch:

jobs:
  build:
    name: Build da aplicação
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Action para ter acesso ao repositorio
      - name: Configuração contexto kuberntes
        uses: azure/k8s-set-context@v5 # https://github.com/marketplace/actions/kubernetes-set-context
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      - name: kubectl get deployments
        uses: abgeo/kubectl-action@1.25.3
        with:
          arg: get deployments        
