# Nome do workflow
name: primeira-pipeline
# Definindo a trigger
on:
  push:
    branches: ["main"]
  workflow_dispatch: # Permite que seja executado manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build project
        run: echo "Compilando o projeto..."
      
      - run: sleep 5

  test:
    runs-on: ubuntu-latest
    needs: build  # <- O job 'test' só inicia depois que 'build' terminar
    steps:
      - name: Run tests
        run: echo "Executando testes unitários..."

  deploy:
    runs-on: ubuntu-latest
    needs: build   # <- O job 'deploy' só inicia depois que 'test' terminar
    steps:
      - name: Deploy to production
        run: echo "Fazendo deploy em produção!"