# Nome do workflow
name: primeira-pipeline
# Definindo a trigger
on:
  push:
    branches: ["main"]
  workflow_dispatch: # Permite que seja executado manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build project
        run: echo "Compilando o projeto..."
      
      - run: sleep 5

  test:
    runs-on: ubuntu-latest
    needs: build 
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Executar testes e gerar relatório
        run: |
          echo "Testes passaram com sucesso!" > resultado-teste.txt
          echo "Data: $(date)" >> resultado-teste.txt
          ls 

      # Passo 1: Salva o arquivo nos servidores do GitHub
      - name: Upload do arquivo de teste
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-testes                # Nome do pacote do artefato
          path: resultado-teste.txt             # Caminho do arquivo que será copiado

  deploy:
    runs-on: ubuntu-latest
    needs: test                                 # Garante que o deploy só roda após o teste terminar
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      
      - name: "Visualizando o repositório"
        run: ls

      # Passo 2: Baixa o arquivo salvo pelo job anterior
      - name: Download do arquivo de teste
        uses: actions/download-artifact@v4
        with:
          name: relatorio-testes                # Deve ser o mesmo nome usado no upload

      # Passo 3: Usa o arquivo baixado
      - name: Ler relatório e fazer Deploy
        run: |
          ls
          echo "Lendo o arquivo copiado do job anterior:"
          cat resultado-teste.txt
          echo "Iniciando o deploy..."
